export const profile = {
  name: "Pedro Calais",
  handle: "@pedrohenriquecalais",
  title: "Desenvolvedor Full Stack. Estudando Data Science e IA",
  location: "Belo Horizonte",
  timezone: "",
  bio: "Dev desde os 16 anos e estudante de Ciência da Computação, com experiência em desenvolvimento de sistemas, automação de processos e análise de dados. Atuação com Python, JavaScript, TypeScript e SQL no desenvolvimento de APIs, integrações, dashboards e soluções voltadas à eficiência operacional.",
  available: true,
  tags: ["Desenvolvedor Full Stack", "Soluções com Inteligência Artificial"],
  stack: ["Python", "TypeScript", "Node.js", "MySQL", "Docker", "Vercel", ],
  email: "pedroalbuquerquecalais@gmail.com",
  phone: "+5531993579590",
  socials: {
    linkedin: "https://www.linkedin.com/in/pedro-henrique-albuquerque-calais-2b7242289/",
    github: "https://github.com/pedrohenriquecalais",
    youtube: "",
    cv: "/docs/Curriculo_PedroCalais_2026.docx",
    whatsapp: "https://wa.me/5531993579590",
  },
};

export const projects = [
  {
    id: 3,
    title: "BlockMind — Plataforma de IA para Roblox",
    description: "Plataforma em desenvolvimento para desenvolvedores de Roblox que querem usar IA para acelerar a criação de jogos, gerar scripts Lua, aprender Roblox Studio e acessar prompts e ferramentas técnicas em um único ambiente.",
    tags: ["IA", "Roblox", "Next.js", "TypeScript"],
    image: "",
    htmlBanner: "/projects/blockmind-banner.html",
    bannerAnchor: "left",
    color: "#09090B",
    link: "",
    summary: {
      description: [
        "A ideia do **BlockMind** nasceu de uma frustração real: ferramentas como ChatGPT, Claude e similares funcionam bem para programação geral, mas falham no contexto do Roblox. Propriedades da engine, eventos de LocalScript, a API do DataStore, as regras de FilteringEnabled — nada disso está bem representado nos modelos genéricos. O código gerado parece certo, mas quebra na prática.",
        "A plataforma centraliza tudo que um desenvolvedor Roblox precisa: assistente treinado no ecossistema, biblioteca de prompts curados, snippets testados, documentação contextual e ferramentas de produtividade. Um ambiente completo para quem leva o desenvolvimento de jogos a sério.",
      ],
      impact: "🚧 Construído por alguém que desenvolve jogos no Roblox e sentiu o problema na prática — não é um wrapper de ChatGPT.",
      storyTitle: "Como surgiu a ideia",
      story: [
        { title: "O gap que nenhuma IA resolve", body: "Modelos genéricos geram código Lua que parece correto mas quebra no Roblox: LocalScripts acessando o servidor, RemoteEvents mal configurados, DataStores sem os yields certos. Os erros são previsíveis porque nenhum modelo foi treinado especificamente para o ambiente. O Roblox AI foi construído para fechar esse gap de contexto." },
        { title: "Acabar com a aba-infinita do dev", body: "Quem desenvolve no Roblox conhece o ciclo: DevHub numa aba, YouTube em outra, DevForum, ChatGPT, projeto antigo aberto no Studio para copiar um trecho. O Roblox AI condensa isso — geração de código, documentação contextual, snippets e explicações em português, tudo em um único ambiente sem interrupção de fluxo." },
        { title: "Uma plataforma, não um produto descartável", body: "A arquitetura foi pensada para crescer além do assistente. O roadmap inclui análise estática de código Lua, geração de assets, templates por gênero de jogo, organização modular de projetos e métricas de performance — construindo algo com visão de produto, não apenas um experimento técnico." },
      ],
      features: [
        "Assistente com contexto real do ecossistema Roblox e das APIs do Studio",
        "Geração de scripts Lua que funcionam — sem adaptação manual",
        "Biblioteca de prompts curados para cenários comuns do desenvolvimento",
        "Snippets testados, organizados por categoria: UI, Physics, DataStore, Combat...",
        "Tutoriais técnicos em português sobre Roblox Studio",
        "Busca contextual por documentação oficial da plataforma",
      ],
      frontend: [
        { tech: "Next.js", uso: "Framework da aplicação" },
        { tech: "React", uso: "Construção da interface" },
        { tech: "TypeScript", uso: "Tipagem estática" },
        { tech: "Tailwind CSS", uso: "Estilização" },
        { tech: "MDX", uso: "Conteúdo técnico e documentação" },
      ],
      backend: [
        { tech: "OpenAI API", uso: "Geração de código e respostas especializadas" },
        { tech: "Vercel", uso: "Deploy e execução das funções serverless" },
      ],
    },
  },
  {
    id: 1,
    title: "MCSA — Plataforma de Gestão",
    description: "Sistema interno de gestão para o escritório de recuperação de créditos Marcelo Candiotto Sociedade de Advogados. Dashboard com autenticação, relatórios e consultas em SQL Server.",
    tags: ["TypeScript", "Next.js", "SQL Server"],
    image: "",
    htmlBanner: "/projects/mcsa-banner.html",
    suppressOverlay: true,
    bannerAnchor: "left",
    color: "#F5F6F8",
    link: "",
    summary: {
      description: [
        "Sistema full stack desenvolvido internamente para o escritório Marcelo Candiotto Sociedade de Advogados. A plataforma centraliza a gestão operacional da recuperação de crédito, reunindo indicadores, consultas ao SQL Server, dashboards interativos e geração de relatórios em um único ambiente.",
        "O backend foi desenvolvido em Flask + Python, utilizando Pandas para processamento de grandes volumes de dados e SQLAlchemy + pyodbc para integração com o SQL Server. O uso de Redis reduziu o tempo de resposta das consultas mais pesadas através de cache inteligente.",
      ],
      story: [
        { title: "Resolver um problema real", body: "O escritório dependia de planilhas e consultas manuais ao banco de dados para acompanhar indicadores. O objetivo foi transformar essas informações em uma plataforma intuitiva, permitindo que qualquer pessoa da operação encontrasse os dados necessários em poucos cliques." },
        { title: "Priorizar desempenho", body: "Grande parte das consultas envolvia milhares de registros. Para manter a interface rápida, o processamento pesado foi concentrado no backend, utilizando cache com Redis e tratamento dos dados antes do envio ao frontend." },
        { title: "Facilitar a adoção", body: "A plataforma precisava ser utilizada imediatamente pela equipe, sem treinamento extenso. Por isso, a interface foi projetada para reduzir cliques, destacar os indicadores mais importantes e apresentar cada informação no contexto correto." },
      ],
      impact: "Utilizado diariamente pela equipe para acompanhar processos, analisar carteiras e gerar relatórios operacionais, substituindo processos manuais que consumiam horas de trabalho semanalmente.",
      frontend: [
        { tech: "React 18", uso: "Framework UI" },
        { tech: "TypeScript", uso: "Tipagem estática" },
        { tech: "Vite", uso: "Bundler / dev server" },
        { tech: "Tailwind CSS", uso: "Estilização" },
        { tech: "Recharts", uso: "Gráficos" },
        { tech: "React Router DOM", uso: "Roteamento" },
        { tech: "Zustand", uso: "Gerenciamento de estado" },
        { tech: "Axios", uso: "Requisições HTTP" },
        { tech: "Framer Motion", uso: "Animações" },
        { tech: "XLSX", uso: "Exportação para Excel" },
      ],
      backend: [
        { tech: "Python", uso: "Linguagem principal" },
        { tech: "Flask", uso: "Framework web / API REST" },
        { tech: "SQLAlchemy", uso: "ORM / conexão com banco" },
        { tech: "Pandas + NumPy", uso: "Processamento de dados" },
        { tech: "pyodbc", uso: "Driver ODBC para SQL Server" },
        { tech: "Gunicorn / Waitress", uso: "Servidor WSGI (produção)" },
        { tech: "Redis", uso: "Cache" },
        { tech: "openpyxl", uso: "Manipulação de Excel" },
      ],
      database: [
        { tech: "SQL Server (MSSQL)", uso: "Banco principal" },
        { tech: "Redis", uso: "Cache de resultados" },
      ],
    },
  },
  {
    id: 2,
    title: "Assistente de IA em Python",
    description: "Assistente de inteligência artificial criado em Python, utilizado como ferramenta de apoio e fonte de pesquisa no desenvolvimento de aplicações.",
    tags: ["Python", "IA", "LLM"],
    image: "",
    htmlBanner: "/projects/ia-banner.html",
    color: "#000510",
    link: "",
    summary: {
      description: "Desenvolvido como projeto prático do curso de Fundamentos da Linguagem Python da Data Science Academy, o assistente surgiu como exercício de aplicação de LLMs via API. Hoje utilizo ele como ferramenta de apoio no dia a dia — pesquisa técnica, geração de snippets e suporte no desenvolvimento de outras aplicações. O projeto me ensinou na prática como consumir modelos de linguagem, gerenciar contexto de conversa e estruturar prompts eficazes.",
      backend: [
        { tech: "Python", uso: "Linguagem principal" },
        { tech: "OpenAI API / Gemini", uso: "Modelo de linguagem (LLM)" },
        { tech: "python-dotenv", uso: "Gerenciamento de variáveis de ambiente" },
        { tech: "Requests / httpx", uso: "Chamadas HTTP à API" },
        { tech: "JSON", uso: "Serialização do histórico de conversa" },
      ],
    },
  },
  {
    id: 4,
    title: "Estudos em Machine Learning",
    description: "Repositório de estudos práticos em ML e LLMs, aplicando modelos e técnicas aprendidas nos cursos da Data Science Academy e Google Cloud.",
    tags: ["Python", "ML", "Data Science"],
    image: "",
    color: "#0d1b2a",
    link: "https://github.com/pedrohenriquecalais",
  },
  {
    id: 5,
    title: "Projetos Web com TypeScript",
    description: "Aplicações web desenvolvidas com TypeScript e JavaScript, explorando automação, APIs e interfaces funcionais alinhadas às boas práticas.",
    tags: ["TypeScript", "JavaScript", "Vercel"],
    image: "",
    color: "#0f1f0f",
    link: "https://github.com/pedrohenriquecalais",
  },
];

export const recentContent = [
  {
    id: 0,
    platform: "linkedin",
    handle: "@pedrohenriquecalais",
    title: "Começar a programar hoje vs alguns anos atrás — o que mudou com a IA?",
    excerpt: "Esses dias fiquei pensando em como deve ser começar na programação hoje. Uma IA consegue gerar em segundos um código que eu levaria horas para construir. Mas saber por que uma solução funciona ainda faz diferença...",
    date: "Jun 2026",
    link: "https://www.linkedin.com/feed/update/urn:li:activity:7472400041710632960/",
    thumbnail: "/posts/cocoboi.gif",
  },
  {
    id: 1,
    platform: "linkedin",
    handle: "@pedrohenriquecalais",
    title: "Minha trajetória no suporte técnico e o que aprendi",
    excerpt: "De estágio na Azapfy até analista na Conecta — o que a vivência com MySQL, MongoDB e logs me ensinou sobre sistemas reais...",
    date: "Fev 2026",
    link: "/blog/suporte-tecnico",
    thumbnail: "/posts/suporte.gif",
  },
  {
    id: 2,
    platform: "linkedin",
    handle: "@pedrohenriquecalais",
    title: "Modelos de IA: Como Escolher a Tecnologia Certa para Cada Aplicação",
    excerpt: "Se você quer parar de adivinhar e entender os critérios técnicos (como latência, infraestrutura e custos) para escolher a IA ideal para cada aplicação, este guia foi feito para você.",
    date: "Em breve",
    link: "https://www.linkedin.com/in/pedro-henrique-albuquerque-calais-2b7242289/",
    thumbnail: null,
  },
  {
    id: 3,
    platform: "linkedin",
    handle: "@pedrohenriquecalais",
    title: "Por que estou estudando Python focado em IA",
    excerpt: "Curso de Fundamentos da linguagem Python da Data Science Academy. Meu plano de evolução de suporte técnico para desenvolvimento com IA...",
    date: "Em breve",
    link: "https://www.linkedin.com/in/pedro-henrique-albuquerque-calais-2b7242289/",
    thumbnail: null,
  },
  {
    id: 4,
    platform: "linkedin",
    handle: "@pedrohenriquecalais",
    title: "Como uso o Git e Postman no dia a dia do suporte",
    excerpt: "Ferramentas que todo analista de suporte deveria dominar. Minha experiência com versionamento e testes de API em ambiente de produção...",
    date: "Em breve",
    link: "https://www.linkedin.com/in/pedro-henrique-albuquerque-calais-2b7242289/",
    thumbnail: null,
  },
];

export const showcase = [
  ...projects.filter((p) => p.image),
  {
    id: 99,
    title: "Negócio IA",
    image: "/carrosel/Negocio_IA.png",
    color: "#1a1a2e",
    tags: [],
    link: "",
  },
  {
    id: 100,
    title: "Negócio IA 2",
    image: "/carrosel/Negocio_IA2.png",
    color: "#1a1a2e",
    tags: [],
    link: "",
  },
];

export const certifications = [
  {
    id: 1,
    title: "Fundamentos da Linguagem Python — Do básico a aplicações de IA",
    issuer: "Data Science Academy",
    date: "Abril 2026",
    badge: "DSA",
    link: "",
    image: "/certificates/python-dsa.jpg",
  },
   {
    id: 2,
    title: "Por dentro da Segurança Cibernética",
    issuer: "SENAI",
    date: "Jun 2026",
    badge: "SENAI",
    link: "https://www.sp.senai.br/consulta-certificado?qrcode=00038491/8509460",
    image: "/certificates/segurança_cinbernetica.png",
  },
  {
    id: 3,
    title: "Soluções de IA no GitHub",
    issuer: "Fundação Bradesco",
    date: "Out 2025",
    badge: "BRADESCO",
    link: "https://lms.ev.org.br/mpls/Web/Lms/Student/PrintCertificateDownload.ashx?uid=12975933&p=WxnJosnXWXTGCsoNKVXSr9Cm39XOSrCW",
    image: "/certificates/ianogithub.jpg",
  },

  {
    id: 4,
    title: "Certificado Investidor 180",
    issuer: "XP Educação",
    date: " SET 2025",
    badge: "XP Educação",
    link: "https://ava.xpeducacao.com.br/d2l/awards/assertions/3923/view",
    image: "/certificates/xp180.png",
  },
  
];

export const journey = {
  education: [
    {
      id: 1,
      institution: "Escola Superior Dom Helder Câmara",
      shortName: "ESDHC",
      degree: "5º Período - Bacharelado em Ciência da Computação",
      period: "jan 2024 — dez 2027",
      current: true,
      description: "Fundamentos da computação, estruturas de dados, algoritmos, desenvolvimento de software, banco de dados, redes e metodologias ágeis.",
      tags: ["Python", "Backend Engineering", "Data Science", "Computer Networks"],
      color: "#ffffff",
      logo: "/logos/domhelder.png",
    },
    {
      id: 2,
      institution: "Data Science Academy",
      shortName: "DSA",
      degree: "Fundamentos da Linguagem Python — Do básico a aplicações de IA",
      period: "Jan 2026 - Abril 2026",
      current: false,
      description: "Curso completo de Python com foco em fundamentos da linguagem e aplicações em inteligência artificial.",
      tags: ["Python", "IA", "Data Science"],
      color: "#ffffff",
      logo: "/logos/DSA.png",
    },
  ],
  experience: [
    {
      id: 1,
      company: "MCSA",
      fullName: "Marcelo Candiotto Sociedade de Advogados",
      role: "Assistente de Tecnologia",
      period: "Nov 2025 — presente",
      current: true,
      roles: [
        { title: "Desenvolvedor Full Stack", period: "Jun 2026 — presente", current: true },
        { title: "Auxiliar de Banco de Dados", period: "Nov 2025 — Jun 2026", current: false },
      ],
      description: "Relatórios e consultas com SQL Server. Desenvolvimento de sistemas internos para automatizar processos e facilitar o acesso a informações jurídicas.",
      tags: ["SQL Server", "Python", "TypeScript"],
      color: "#ffffff",
      logo: "/logos/mcsa.png",
    },
    {
      id: 2,
      company: "Conecta",
      fullName: "Conecta",
      role: "Suporte Técnico em Redes e Infraestrutura",
      period: "jul 2025 — Nov 2025",
      current: false,
      description: "Diagnósticos e resolução de falhas de conectividade, configuração de equipamentos de rede e monitoramento de desempenho.",
      tags: ["Redes", "TCP/IP", "Suporte"],
      color: "transparent",
      logo: "/logos/conecta.svg",
    },
    {
      id: 3,
      company: "Azapfy",
      fullName: "Azapfy",
      role: "Estagiário de Analista de Suporte",
      period: "jan 2025 — jul 2025",
      current: false,
      description: "Suporte a usuários, testes em produção e análise de logs. Consultas e atualizações com MySQL e MongoDB.",
      tags: ["MySQL", "MongoDB", "Logs"],
      color: "#ffffff",
      logo: "/logos/azapfy.png",
    },
  ],
};
